Kinematics exercise link: https://canvas.education.lu.se/courses/37285/assignments/257751



In [2]:
import numpy as np

In [7]:
o_0 = np.eye(3)

# When showing results split them into the column vectors as e1, e2, e3 were given

# Rotate around y by alfa
a = 10

rotation = np.array([
    [np.cos(a), 0, np.sin(a)],
    [0, 1, 0],
    [-np.sin(a), 0, np.cos(a)]
]
)

print(o_0)
print(rotation)
print(o_0 @ rotation)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-0.83907153  0.         -0.54402111]
 [ 0.          1.          0.        ]
 [ 0.54402111  0.         -0.83907153]]
[[-0.83907153  0.         -0.54402111]
 [ 0.          1.          0.        ]
 [ 0.54402111  0.         -0.83907153]]


In [8]:
print(rotation)  # 1b

[[-0.83907153  0.         -0.54402111]
 [ 0.          1.          0.        ]
 [ 0.54402111  0.         -0.83907153]]


In [10]:
# c:

a = np.pi/4

rotation = np.array([
    [np.cos(a), 0, np.sin(a)],
    [0, 1, 0],
    [-np.sin(a), 0, np.cos(a)]
]
)

#print(o_0)
#print(rotation)
print(o_0 @ rotation)
# alfa pi/4 is 45 degrees, so each transformed axis should have size 1/sqrt(2) which we can see is true.


[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


In [13]:
# d: This can not be done using a 4x4 matrix, we can instead use a 3x4 matrix which is often called a transformation matrix.

# The matrix would look like this:

t = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 0, 1]]
)
print(t)

[[1 0 0 0]
 [0 1 0 1]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
# 2a: find the DH parameters for the coordinate frames

# d offset along previous z to the common normal
# θ angle about previous z from old to new x
# r length of the common normal
# a (alfa) angle about common normal from old z to new z

# z0 frame, x_0 positive, y_0 negative
# z1 frame, x_1 positive, y_1 negative, l1 y space away from z0
# z2 frame, x_2 positive, y_2 positive, l2 y space away from z0

# Using x as common normal, according to the image theta_1 and theta_2 are both 0.
#       d   a       r   theta
# z1:   0   0       l1  theta_1
# z2:   0   -pi     l2  theta_2

In [14]:
# 2b:
# T_x_y = > Z_(x-1) @ X_n
l1 = 1
l2 = 1
trans0 = np.array(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ]
)

trans1 = np.array(
    [
        [1, 0, 0, l1],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ]
)

rot_1_0 = np.array(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ]
)

T_0_to_1 = trans1 @ rot_1_0

trans2 = np.array(
    [
        [1, 0, 0, l2],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]
    ]
)

a_n = -np.pi
# Rotating -pi around x
rot_2_1 = np.array(
    [
        [1, 0, 0, 0],
        [0, np.cos(a_n), -np.sin(a_n), 0],
        [0, np.sin(a_n), np.cos(a_n), 0],
        [0, 0, 0, 1]
    ]
)
T_1_to_2 = trans2 @ rot_2_1
T_0_to_2 = T_0_to_1 @ T_1_to_2

print(T_0_to_2)

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00  2.0000000e+00]
 [ 0.0000000e+00 -1.0000000e+00  1.2246468e-16  0.0000000e+00]
 [ 0.0000000e+00 -1.2246468e-16 -1.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [16]:
# We now must get T_2_to_1, it is logical that T_2_to_1 should be the inverse of T_1_to_2
# TODO: Motivate this more
T_2_to_1 = np.linalg.inv(T_1_to_2)
print(T_2_to_1)  # This can be seen to be correct as the dx now is correct and the rotation matrix is also

[[ 1.0000000e+00  0.0000000e+00  0.0000000e+00 -1.0000000e+00]
 [-0.0000000e+00 -1.0000000e+00 -1.2246468e-16 -0.0000000e+00]
 [-0.0000000e+00  1.2246468e-16 -1.0000000e+00 -0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00  1.0000000e+00]]


In [ ]:
# 2c

# The difference between a homogeneous transformation matrix and a rotation matrix is that a rotation matrix only rotates the frame but does not displace it linearly which a transformation matrix can do.

In [65]:
from sympy import Matrix, Symbol, cos, sin, print_latex, pi
# 3

# 3a:

l = Symbol("l") # All 3 links have this length
# We start with finding all the transform matrices

T1 = Matrix([
    [1, 0, l ],
    [0, 1, 0 ],
    [0, 0, 1 ],
])
T3 = T2 = T1  # All have the same link lengths

# I will see the first joint as rotating around z and the rest around x
theta1, theta2, theta3 = Symbol("t_1"), Symbol("t_2"), Symbol("t_3")
rot1 = Matrix([
    [cos(theta1), -sin(theta1), 0],
    [sin(theta1), cos(theta1), 0],
    [0, 0, 1],
])

rot2 = Matrix([
    [cos(theta2), -sin(theta2), 0],
    [sin(theta2), cos(theta2), 0],
    [0, 0, 1],
])

rot3 = Matrix([
    [cos(theta3), -sin(theta3), 0],
    [sin(theta3), cos(theta3), 0],
    [0, 0, 1],
])
T3_0_to_2 = Matrix((((Matrix(np.eye(3)) @ rot1 @ T1) @ (rot2 @ T2)) @ (rot3 @ T3)))
#print_latex(T3_0_to_2)
T3_0_to_2.simplify()  # The function from angle to position for x is given from column 3 row 1 in the matrix, and for y in col 3 row 2.
theta_to_x = T3_0_to_2[2]
theta_to_y = T3_0_to_2[5]
T3_0_to_2

1.0*l*(cos(t_1) + cos(t_1 + t_2) + cos(t_1 + t_2 + t_3))
1.0*l*(sin(t_1) + sin(t_1 + t_2) + sin(t_1 + t_2 + t_3))


Matrix([
[1.0*cos(t_1 + t_2 + t_3), -1.0*sin(t_1 + t_2 + t_3), 1.0*l*(cos(t_1) + cos(t_1 + t_2) + cos(t_1 + t_2 + t_3))],
[1.0*sin(t_1 + t_2 + t_3),  1.0*cos(t_1 + t_2 + t_3), 1.0*l*(sin(t_1) + sin(t_1 + t_2) + sin(t_1 + t_2 + t_3))],
[                       0,                         0,                                                      1.0]])

In [58]:
# 3b.
"""
To check your solution, compute the forward kinematics for the following joint
configurations (θ1,θ2,θ3): (0, 0, 0),(0, π/4, π/4). Are the resulting homogeneous
transformation matrices in agreement with what you would expect? Draw the
robot configuration in the respective case and mark the end-effector / tool frame.
"""
T3_0_to_2.subs({theta1: 0, theta2: 0, theta3: 0, l: 2})

Matrix([
[1.0,   0, 6.0],
[  0, 1.0,   0],
[  0,   0, 1.0]])

In [59]:
T3_0_to_2.subs({theta1: 0, theta2: pi/4, theta3: pi/4, l: 2})

Matrix([
[  0, -1.0, 1.0*sqrt(2) + 2.0],
[1.0,    0, 1.0*sqrt(2) + 2.0],
[  0,    0,               1.0]])

In [67]:
# 3c: TODO verify if true
# As we have three joints in a 2D situation all reachable points have an infinite amount of possible joint value combinations.

# It is also possible to find a close form solution for the inverse kinematics problem here, it is (somewhat) simply required to invert the theta to x and theta to y functions.