Kinematics exercise link: https://canvas.education.lu.se/courses/37285/assignments/257751



In [2]:
import numpy as np

In [7]:
o_0 = np.eye(3)

# When showing results split them into the column vectors as e1, e2, e3 were given

# Rotate around y by alfa
a = 10

rotation = np.array([
    [np.cos(a), 0, np.sin(a)],
    [0, 1, 0],
    [-np.sin(a), 0, np.cos(a)]
]
)

print(o_0)
print(rotation)
print(o_0 @ rotation)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-0.83907153  0.         -0.54402111]
 [ 0.          1.          0.        ]
 [ 0.54402111  0.         -0.83907153]]
[[-0.83907153  0.         -0.54402111]
 [ 0.          1.          0.        ]
 [ 0.54402111  0.         -0.83907153]]


In [8]:
print(rotation)  # 1b

[[-0.83907153  0.         -0.54402111]
 [ 0.          1.          0.        ]
 [ 0.54402111  0.         -0.83907153]]


In [10]:
# c:

a = np.pi/4

rotation = np.array([
    [np.cos(a), 0, np.sin(a)],
    [0, 1, 0],
    [-np.sin(a), 0, np.cos(a)]
]
)

#print(o_0)
#print(rotation)
print(o_0 @ rotation)
# alfa pi/4 is 45 degrees, so each transformed axis should have size 1/sqrt(2) which we can see is true.


[[ 0.70710678  0.          0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]


In [13]:
# d: This can not be done using a 4x4 matrix, we can instead use a 3x4 matrix which is often called a transformation matrix.

# The matrix would look like this:

t = np.array([
    [1, 0, 0, 0],
    [0, 1, 0, 1],
    [0, 0, 1, 0],
    [0, 0, 0, 1]]
)
print(t)

[[1 0 0 0]
 [0 1 0 1]
 [0 0 1 0]
 [0 0 0 1]]
